language: go

go:
  - 1.6

install:
  - go get -v -t .
  - go get github.com/mattn/goveralls
  - go install github.com/mattn/goveralls

script:
  - go test -v -race -coverprofile cover.out
  - goveralls -service travis-ci -repotoken $COVERALLS_TOKEN -coverprofile cover.out
